function dh_dx = rigidBodyOutputsDerivatives(v_Bx,v_By,v_Bz,omega_Bx,omega_By,omega_Bz,f_Bx,f_By,f_Bz,mu_Bx,mu_By,mu_Bz,I_Bxx,I_Byy,I_Bzz,m)
%RIGIDBODYOUTPUTSDERIVATIVES
%    DH_DX = RIGIDBODYOUTPUTSDERIVATIVES(V_BX,V_BY,V_BZ,OMEGA_BX,OMEGA_BY,OMEGA_BZ,F_BX,F_BY,F_BZ,MU_BX,MU_BY,MU_BZ,I_BXX,I_BYY,I_BZZ,M)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    26-Jul-2014 12:19:19

t2 = 1.0./m;
dh_dx = reshape([0.0,-omega_Bz,omega_By,0.0,0.0,0.0,0.0,0.0,0.0,omega_Bz,0.0,-omega_Bx,0.0,0.0,0.0,0.0,0.0,0.0,-omega_By,omega_Bx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,v_Bz,-v_By,0.0,0.0,0.0,0.0,0.0,0.0,-v_Bz,0.0,v_Bx,0.0,0.0,0.0,0.0,0.0,0.0,v_By,-v_Bx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[9, 12]);
