function df_dx = rigidBodyDynamicsDerivatives(v_Bx,v_By,v_Bz,omega_Bx,omega_By,omega_Bz,f_Bx,f_By,f_Bz,mu_Bx,mu_By,mu_Bz,I_Bxx,I_Byy,I_Bzz,m)
%RIGIDBODYDYNAMICSDERIVATIVES
%    DF_DX = RIGIDBODYDYNAMICSDERIVATIVES(V_BX,V_BY,V_BZ,OMEGA_BX,OMEGA_BY,OMEGA_BZ,F_BX,F_BY,F_BZ,MU_BX,MU_BY,MU_BZ,I_BXX,I_BYY,I_BZZ,M)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    26-Jul-2014 12:19:19

t2 = 1.0./m;
t3 = 1.0./I_Bxx;
t4 = 1.0./I_Byy;
t5 = I_Byy.*omega_By;
t6 = 1.0./I_Bzz;
t7 = I_Bxx.*omega_Bx;
df_dx = reshape([0.0,-omega_Bz,omega_By,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,omega_Bz,0.0,-omega_Bx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-omega_By,omega_Bx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,v_Bz,-v_By,0.0,-t4.*(I_Bxx.*omega_Bz-I_Bzz.*omega_Bz),-t6.*(t5-I_Bxx.*omega_By),0.0,0.0,0.0,0.0,0.0,0.0,-v_Bz,0.0,v_Bx,t3.*(I_Byy.*omega_Bz-I_Bzz.*omega_Bz),0.0,t6.*(t7-I_Byy.*omega_Bx),0.0,0.0,0.0,0.0,0.0,0.0,v_By,-v_Bx,0.0,t3.*(t5-I_Bzz.*omega_By),-t4.*(t7-I_Bzz.*omega_Bx),0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,0.0],[12, 12]);
